name: Build Test
on:
  workflow_dispatch:
    
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            args: '--bundles msi'
          - platform: ubuntu-22.04
            args: '--bundles deb,rpm,appimage'
          - platform: macos-latest
            target: 'aarch64-apple-darwin' # Mac Silicon (M1/M2/M3)
            args: '--bundles dmg --target aarch64-apple-darwin'
          - platform: macos-latest
            target: 'x86_64-apple-darwin' # Mac Intel
            args: '--bundles dmg --target x86_64-apple-darwin'

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }} # Si es Mac, instala el compilador extra

      - name: Prepare Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies (Linux only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: Install app dependencies and build web
        run: pnpm i --no-frozen-lockfile && pnpm run build # Change this to npm, yarn or pnpm.    

      - name: Verify Tauri Build Compiles
        uses: tauri-apps/tauri-action@v0
        with:
          includeRelease: true